apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
      - name: my-spring-app
        image: srbest2/test-image
        ports:
        - containerPort: 8080
#      terminationGracePeriodSeconds: 120 #DOES NOT HAVE ANY EFFECT
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-spring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
